spring.application.name=student-management

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database - this is the important fix!
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.show-sql=true


# Set overall log level
logging.level.root=INFO

# Set specific package log levels
logging.level.com.student.student_management=DEBUG

# Log output format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n